#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &

# panel
./.config/polybar/launch.sh &

# Set some bsp specific stuff
bspc monitor -d I II III IV V 

bspc config window_gap 7
bspc config border_width 1
bspc config top_padding 25
bspc config focused_border_color "#b9bd86"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
